# Generated by Django 3.1.2 on 2020-10-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
